In [1]:
# Generic inputs for most ML tasks
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn import tree
#import graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingClassifier
pd.options.display.float_format = '{:,.2f}'.format

# setup interactive notebook mode
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

from IPython.display import display, HTML

from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('Datasets/in-vehicle-coupon-recommendation.csv')
data.head()
data.isna().sum()
data = data.dropna()
data.isna().sum()
data = data.drop(columns = ['car'],axis = 1)

,destination,passanger,weather,temperature,time,coupon,expiration,gender,age,maritalStatus,...,CoffeeHouse,CarryAway,RestaurantLessThan20,Restaurant20To50,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,Y
0,No Urgent Place,Alone,Sunny,55,2PM,Restaurant(<20),1d,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,0,0,0,1,1
1,No Urgent Place,Friend(s),Sunny,80,10AM,Coffee House,2h,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,0,0,0,1,0
2,No Urgent Place,Friend(s),Sunny,80,10AM,Carry out & Take away,2h,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,1,0,0,1,1
3,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,2h,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,1,0,0,1,0
4,No Urgent Place,Friend(s),Sunny,80,2PM,Coffee House,1d,Female,21,Unmarried partner,...,never,NaN,4~8,1~3,1,1,0,0,1,0

destination                 0
passanger                   0
weather                     0
temperature                 0
time                        0
coupon                      0
expiration                  0
gender                      0
age                         0
maritalStatus               0
has_children                0
education                   0
occupation                  0
income                      0
car                     12576
Bar                       107
CoffeeHouse               217
CarryAway                 151
RestaurantLessThan20      130
Restaurant20To50          189
toCoupon_GEQ5min            0
toCoupon_GEQ15min           0
toCoupon_GEQ25min           0
direction_same              0
direction_opp               0
Y                           0
dtype: int64

destination             0
passanger               0
weather                 0
temperature             0
time                    0
coupon                  0
expiration              0
gender                  0
age                     0
maritalStatus           0
has_children            0
education               0
occupation              0
income                  0
car                     0
Bar                     0
CoffeeHouse             0
CarryAway               0
RestaurantLessThan20    0
Restaurant20To50        0
toCoupon_GEQ5min        0
toCoupon_GEQ15min       0
toCoupon_GEQ25min       0
direction_same          0
direction_opp           0
Y                       0
dtype: int64

In [3]:
from sklearn.preprocessing import OneHotEncoder

def get_ohe(df, col):
    ohe = OneHotEncoder(drop='first', handle_unknown='error', sparse=False, dtype='int')
    ohe.fit(df[[col]])
    temp_df = pd.DataFrame(data=ohe.transform(df[[col]]), columns=ohe.get_feature_names())
    # If you have a newer version, replace with columns=ohe.get_feature_names_out()
    df.drop(columns=[col], axis=1, inplace=True)
    df = pd.concat([df.reset_index(drop=True), temp_df], axis=1)
    return df

data = get_ohe(data, 'destination')
data = get_ohe(data, 'passanger')
data = get_ohe(data, 'weather')
data = get_ohe(data, 'time')
data = get_ohe(data, 'coupon')
data = get_ohe(data, 'expiration')
data = get_ohe(data, 'gender')
data = get_ohe(data, 'maritalStatus')
data = get_ohe(data, 'education')
data = get_ohe(data, 'occupation')
data = get_ohe(data, 'income')
data = get_ohe(data, 'CoffeeHouse')
data = get_ohe(data, 'Bar')
data = get_ohe(data, 'RestaurantLessThan20')
data = get_ohe(data, 'Restaurant20To50')
data = get_ohe(data, 'CarryAway')   
    
X_train, X_test, y_train, y_test = train_test_split(data.drop(columns = ['Y'],axis = 1),data['Y'], test_size=0.20, random_state = 2)
X_train
X_test
y_train
y_test

#finaltest = StandardScaler()
#X_train = pd.DataFrame(finaltest.fit_transform(X_train), columns = X_train.columns,index=X_train.index)
#X_test = pd.DataFrame(df_sub.transform(X_test), columns = X_test.columns, index=X_test.index)

/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
/Users/shanghuahao/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,temperature,age,has_children,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,x0_No Urgent Place,x0_Work,...,x0_$37500 - $49999,x0_$87500 - $99999,x0_4~8,x0_less1,x0_less1,x0_never,x0_less1,x0_less1,x0_never,x0_4~8
11,55,26,0,1,1,0,0,1,1,0,...,0,0,1,0,1,0,0,0,1,1
83,55,26,0,1,1,1,0,1,0,1,...,0,1,0,1,0,0,0,0,0,0
23,80,41,1,1,0,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
91,80,21,0,1,0,0,0,1,1,0,...,1,0,0,1,0,1,1,1,0,0
35,55,41,1,1,0,0,1,0,0,0,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,55,26,1,1,0,0,0,1,1,0,...,0,1,0,1,0,1,0,1,0,0
22,55,41,1,1,0,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
72,30,26,0,1,0,0,0,1,1,0,...,0,1,0,1,0,0,0,0,0,0
15,80,26,0,1,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,1,1
40,80,41,1,1,1,0,0,1,0,1,...,0,0,0,0,0,1,0,1,0,0

,temperature,age,has_children,toCoupon_GEQ5min,toCoupon_GEQ15min,toCoupon_GEQ25min,direction_same,direction_opp,x0_No Urgent Place,x0_Work,...,x0_$37500 - $49999,x0_$87500 - $99999,x0_4~8,x0_less1,x0_less1,x0_never,x0_less1,x0_less1,x0_never,x0_4~8
36,55,41,1,1,1,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,0
102,80,21,0,1,0,0,1,0,0,0,...,1,0,0,1,0,1,1,1,0,0
13,55,26,0,1,0,0,1,0,0,0,...,0,0,1,0,1,0,0,0,1,1
54,55,26,1,1,1,0,0,1,1,0,...,0,1,0,1,0,1,0,1,0,0
27,80,41,1,1,1,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
48,80,26,1,1,1,0,0,1,1,0,...,0,1,0,1,0,1,0,1,0,0
62,80,26,1,1,0,0,1,0,0,1,...,0,1,0,1,0,1,0,1,0,0
2,80,26,0,1,0,0,0,1,1,0,...,0,0,1,0,1,0,0,0,1,1
30,80,41,1,1,1,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
94,55,21,0,1,1,0,0,1,1,0,...,1,0,0,1,0,1,1,1,0,0
64,55,26,1,1,1,0,0,1,0,1,...,0,1,0,1,0,1,0,1,0,0
14,55,26,0,1,1,0,0,1,0,0,...,0,0,1,0,1,0,0,0,1,1
24,80,41,1,1,1,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
100,30,21,0,1,1,0,0,1,0,0,...,1,0,0,1,0,1,1,1,0,0
21,55,26,0,1,1,0,0,1,0,1,...,0,0,1,0,1,0,0,0,1,1
16,55,26,0,1,1,1,0,1,0,1,...,0,0,1,0,1,0,0,0,1,1
0,55,26,0,1,0,0,0,1,1,0,...,0,0,1,0,1,0,0,0,1,1
3,80,26,0,1,1,0,0,1,1,0,...,0,0,1,0,1,0,0,0,1,1
57,55,26,1,1,1,0,0,1,0,0,...,0,1,0,1,0,1,0,1,0,0
44,80,26,1,1,0,0,0,1,1,0,...,0,1,0,1,0,1,0,1,0,0
28,55,41,1,1,1,0,0,1,1,0,...,0,0,0,0,0,1,0,1,0,0
96,30,21,0,1,1,0,0,1,1,0,...,1,0,0,1,0,1,1,1,0,0

11    1
83    1
23    1
91    1
35    0
     ..
43    1
22    1
72    0
15    1
40    0
Name: Y, Length: 86, dtype: int64

36     1
102    0
13     0
54     1
27     0
48     1
62     1
2      1
30     0
94     0
64     1
14     0
24     0
100    0
21     0
16     1
0      1
3      0
57     0
44     1
28     1
96     1
Name: Y, dtype: int64

In [4]:
model5 = GradientBoostingClassifier(random_state=2, min_samples_split = 5, min_samples_leaf = 3)

model5 = model5.fit(X_train, y_train) 

model5.score(X_train,y_train)

0.9883720930232558

In [5]:
test_output = pd.DataFrame(model5.predict(X_test), index = X_test.index, columns = ['P-Y'])
test_output.head()

test_output = test_output.merge(y_test, left_index = True, right_index = True)
test_output.head()
mean_absolute_error = abs(test_output['P-Y'] - test_output['Y']).mean()
print('Mean absolute error is ')
print(mean_absolute_error)
print('Fraction MAE is ')
print(mean_absolute_error / test_output['Y'].mean())

     P-Y
36     0
102    1
13     0
54     1
27     0

     P-Y  Y
36     0  1
102    1  0
13     0  0
54     1  1
27     0  0

Mean absolute error is
0.45454545454545453
Fraction MAE is
0.9090909090909091